# Generated by Django 3.1.1 on 2020-10-07 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='body',
            field=models.TextField(default=-1.0),
            preserve_default=False,
        ),
    ]
