# Generated by Django 3.1.1 on 2020-10-07 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_applications_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='link_comment',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='applications',
            name='url',
            field=models.URLField(max_length=512, null=True),
        ),
    ]
