# Generated by Django 3.1.1 on 2020-10-13 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationsPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
            ],
            options={
                'verbose_name': 'applicationspost',
            },
        ),
    ]
