# Generated by Django 3.1.1 on 2020-10-29 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20201029_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manuale',
            name='img',
        ),
    ]
