# Generated by Django 3.1.1 on 2020-10-29 12:17

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_remove_manuale_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bazaligjore',
            name='url',
        ),
        migrations.RemoveField(
            model_name='formular',
            name='url',
        ),
        migrations.RemoveField(
            model_name='sherbime',
            name='url',
        ),
        migrations.AlterField(
            model_name='bazaligjore',
            name='title',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='formular',
            name='title',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='sherbime',
            name='title',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
