# Generated by Django 3.1.1 on 2020-10-29 15:01

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_manuale_po'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manuale',
            name='po',
        ),
        migrations.AddField(
            model_name='manuale',
            name='link',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=datetime.datetime(2020, 10, 29, 15, 1, 40, 284340, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='manuale',
            name='title',
            field=models.TextField(),
        ),
    ]
