# Generated by Django 3.1.1 on 2020-10-29 15:03

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_auto_20201029_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='bazaligjore',
            name='link',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=datetime.datetime(2020, 10, 29, 15, 3, 44, 234471, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bazaligjore',
            name='title',
            field=models.TextField(),
        ),
    ]
