# Generated by Django 3.1.1 on 2020-10-29 15:10

import ckeditor_uploader.fields
import datetime
from django.db import migrations
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_auto_20201029_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applications',
            name='body',
        ),
        migrations.AlterField(
            model_name='applications',
            name='url',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=datetime.datetime(2020, 10, 29, 15, 10, 59, 253488, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
