# Generated by Django 3.1.1 on 2020-10-29 15:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_auto_20201029_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='body',
            field=models.TextField(default=datetime.datetime(2020, 10, 29, 15, 14, 29, 371632, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applications',
            name='url',
            field=models.URLField(max_length=512, null=True),
        ),
    ]
