# Generated by Django 3.1.1 on 2020-10-30 12:11

import ckeditor_uploader.fields
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_auto_20201029_1514'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applications',
            old_name='body',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='applications',
            name='url',
        ),
        migrations.AlterField(
            model_name='applications',
            name='link_comment',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
