# Generated by Django 3.1.1 on 2020-10-30 15:39

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_auto_20201030_1212'),
    ]

    operations = [
        migrations.CreateModel(
            name='MostUsedApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('link', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
            options={
                'verbose_name': 'mostusedapp',
            },
        ),
    ]
